### ISSUE TITLE
Python logo png file was moved

### ISSUE THREAD

**Issue by kbaikov** [talkpython/static-sites-with-sphinx-and-markdown-course#2]
The first time the author uses the directive {download}`logofile.png` the logofile is moved to _build/_download/hashthing/logofile.png.
The Author mentions exactly that. 

However the file is MOVED from the root dir and is not available for other directives anymore. e.g. {image} or ![]() link.

This is not a biggie, but still.

Thank you for the course.

**Comment by pauleveritt** [comment]
Can you give a reproducible case for this? Whenever I used it, my PNG was still there in my source directory.

**Comment by kbaikov** [comment]
Actually i can't reproduce it anymore.
Was to hasty to create a bug.

Sorry. Closing.

**Comment by pauleveritt** [comment]
No need to apologize, I'm just glad you're giving it a try. Please report anything you find.
