### ISSUE TITLE
# Ch 2. Setup - Live Reload - Getting 404 when run

### ISSUE THREAD

**Issue by gloc-mike** [talkpython/static-sites-with-sphinx-and-markdown-course#5]
Hi,

I'm having an issue just getting the `sphinx-quickstart` generated site up and running. :(

I'm on macOS (Catalina 10.15.7), using `pipenv` for virtualization and using Python 3.10.1. 

Apart from that, nothing strikingly different from the course but I'm just getting a 404 message when I run the `run_livereload.py` script and go to the local host address that's given.

Please view a copy of the code here: [Schlockchain](https://github.com/gloc-mike/schlockchain)

Any ideas to help resolve this would be very much appreciated! :)

Thanks
Michael

**Comment by gloc-mike** [comment]
Hi,

I found out what was going on. The site had not been built! Makes sense now, looking at it in hindsight. :)

There is a step missing from the videos though to specifically build the site using `make html`.

Running `run_livereload.py` doesn't build the site if nothing else has been edited so I stumbled on that bit.

I guess that hiding the `_build` folder in PyCharm (Exclude folder) might not be a good idea to start with since I didn't see that the site had not actually been built. In my case, PyCharm hid the `_build` folder when it was excluded. I only discovered that it was empty when I jumped onto a Terminal session and navigated to the `_build` folder.

Anyway, sorted!

Thanks
Michael

**Comment by mikeckennedy** [comment]
Hi @gloc-mike Sorry you got hung up but thanks for all the extra info and what you did to get it unstuck. Cheers, Michael.

**Comment by pauleveritt** [comment]
My apologies, I thought I had in the flow the first edit which would trigger things. I probably should have the run_livereload.py do a build on initial startup.

**Comment by gloc-mike** [comment]
No worries Paul! You can't spoon feed us everything! ;)

I went through the videos a few times thinking "I must have missed something, let me check again"! :)

It was actually a couple of your videos (Setup: 4 (Making a Sphinx Site) & 5 (Live reload)) that gave me a hint as to what my problem really was though.

The Terminal in video 4 looked like this:
![Screen Shot 2022-01-21 at 2 10 28 pm](https://user-images.githubusercontent.com/2324626/150459960-28874134-4842-421a-94d9-0d16ee7e871b.png)

And the Terminal in video 5 looked like this:
![Screen Shot 2022-01-21 at 2 09 45 pm](https://user-images.githubusercontent.com/2324626/150460008-ef179d30-23ee-4e1c-a235-701ef88a06c3.png)

So I checked the `_build` folder in a Terminal session (which I couldn't see in PyCharm) and noticed it was empty and the penny finally dropped (face palm). :)

Thanks for the follow-up. Very much appreciated. And thanks for the course!
Michael
