### ISSUE TITLE
make html missing

### ISSUE THREAD

**Issue by fcarvalhopacheco** [talkpython/static-sites-with-sphinx-and-markdown-course#9]
Hi,

Great course! 

I got stuck [watching this video here](https://training.talkpython.fm/player/course/static-sites-with-sphinx-and-markdown/lecture/380205). That's because I believe you forgot to mention how to build the HTML using `make html`. In other words, the folder `_build` is still empty after watching [Make a sphinx site](https://training.talkpython.fm/player/course/static-sites-with-sphinx-and-markdown/lecture/380204). Perhaps you forgot to record that part? 

Either way, I found your post [here](https://www.jetbrains.com/pycharm/guide/tutorials/sphinx_sites/setup/) 

I am also creating my guide using `conda` to help me through the training. Please [check here](https://github.com/fcarvalhopacheco/sphinx-fcp)

Thanks again!!

Cheers
Fernando

**Comment by pauleveritt** [comment]
Hi, in this course I show the use of a `livereload` script. You run it and then, as you edit your content, it re-runs Sphinx and tells the browser to update the page.

**Comment by fcarvalhopacheco** [comment]
Yes! super cool by the way! 

I think I had two issues regarding that. 
1. I had to re-install xcode on my mac: `xcode-select --install` ... `make` was breaking
2. my `conda` .env was also giving problems to sphinx. So... 
```python 
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '.env']   
```

Then, I actually ran 
```sh
sphinx-build -b html ../sphinx-fcp _build/html  
```

before running 
```sh
python ./run_livereload.py
```

But all is good now! 

Thanks again... 

Cheers
FP

**Comment by fcarvalhopacheco** [comment]
Thanks!
